from typing import List, Sequence, Tuple, Union, overload

class Tensor:
    @overload
    def __init__(self, values: Sequence[float], shape: Sequence[int]) -> None: ...
    @overload
    def __init__(self, shape: Sequence[int]) -> None: ...
    def numel(self) -> int: ...
    def dim(self) -> int: ...
    def shape(self) -> List[int]: ...
    def strides(self) -> List[int]: ...
    def at(self, indices: Sequence[int]) -> float: ...
    def __getitem__(self, indices: Union[int, Tuple[int, ...], Sequence[int]]) -> float: ...
    def __setitem__(self, indices: Union[int, Tuple[int, ...], Sequence[int]], value: float) -> None: ...
    def __add__(self, other: "Tensor") -> "Tensor": ...
    def __sub__(self, other: "Tensor") -> "Tensor": ...
    def __mul__(self, other: "Tensor") -> "Tensor": ...
    def __truediv__(self, other: "Tensor") -> "Tensor": ...
    def __repr__(self) -> str: ...
